const Router = require('express')
const router = new Router

const orderRouter=require('./order.router.js')
const localityRouter=require('./locality.router.js')
const streetRouter=require('./street.router.js')
const deliveryRouter=require('./delivery.router.js')
const bouquetRouter=require('./bouquet.router')
const flowerRouter=require('./flower.routes.js')
const bouquetCompositionRouter = require('./bouquet.composition.routes.js')
const bouquetCategoryRouter = require('./bouquet.category.routes.js')
const orderCompositionRouter = require('./order.composition.routes.js')
const userRouter = require('./user.router.js')
const basketRouter = require('./basket.router.js')
const selectedRouter = require('./selected.router.js')
const employeeRouter = require('./employee.router.js')
const wrapperRouter = require('./wrapper.routes.js')
const postRouter = require('./post.router.js')
const categoryRouter = require('./category.router.js')
const wrapperCategoryRouter = require('./wrapper.category.router.js')
const discountRouter = require('./discount.router.js')


router.use('/user',userRouter)
router.use('/employee',employeeRouter)
router.use('/post',postRouter)
router.use('/basket',basketRouter)
router.use('/selected',selectedRouter)
router.use('/discount',discountRouter)
router.use('/order',orderRouter)
router.use('/ordercomposition',orderCompositionRouter)
router.use('/locality',localityRouter)
router.use('/street',streetRouter)
router.use('/delivery',deliveryRouter)
router.use('/flower',flowerRouter)
router.use('/bouquet',bouquetRouter)
router.use('/bouquetcomposition',bouquetCompositionRouter)
router.use('/bouquetcategory',bouquetCategoryRouter)
router.use('/wrapper',wrapperRouter)
router.use('/category',categoryRouter)
router.use('/wrapper_category',wrapperCategoryRouter)


module.exports = router