export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const Boquet_ROUTE = '/boquet'
export const IndBoquet_ROUTE = '/Indboquet'
export const Basket_ROUTE = '/basket'